#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
MODE="${OMFG_LAYER_MODE:-passthrough}"
VKCUBE_COUNT="${OMFG_VKCUBE_COUNT:-120}"
VKCUBE_TIMEOUT_SEC="${OMFG_VKCUBE_TIMEOUT_SEC:-20}"
VKCUBE_PRESENT_MODE="${OMFG_VKCUBE_PRESENT_MODE:-}"
VKCUBE_EXTRA_ARGS="${OMFG_VKCUBE_EXTRA_ARGS:-}"
ARTIFACT_SUFFIX="${OMFG_VKCUBE_ARTIFACT_SUFFIX:-}"

# shellcheck disable=SC1091
source "${ROOT_DIR}/scripts/_omfg_layer_impl.sh"

REMOTE_BASE="${1:-${OMFG_LAYER_REMOTE_BASE_DEFAULT}}"
RUN_NAME="${MODE}"
if [[ -n "${ARTIFACT_SUFFIX}" ]]; then
  RUN_NAME="${MODE}-${ARTIFACT_SUFFIX}"
fi
ARTIFACT_DIR="${ROOT_DIR}/${OMFG_LAYER_ARTIFACT_ROOT_REL}/vkcube/${RUN_NAME}"

mkdir -p "${ARTIFACT_DIR}"

PRESENT_MODE_ARG=""
if [[ -n "${VKCUBE_PRESENT_MODE}" ]]; then
  PRESENT_MODE_ARG="--present_mode ${VKCUBE_PRESENT_MODE}"
fi

REMOTE_SCRIPT=$(cat <<EOF
set -euo pipefail
mkdir -p ${REMOTE_BASE}
rm -f ${REMOTE_BASE}/omfg-vkcube.log ${REMOTE_BASE}/vkcube.stdout
set -a
source /run/user/1000/gamescope-environment
set +a
export DISPLAY=:0
export XDG_RUNTIME_DIR=/run/user/1000
export XAUTHORITY=\$(ls -1 /run/user/1000/xauth_* | head -1)
export DISABLE_GAMESCOPE_WSI=1
export ${OMFG_LAYER_ENABLE_ENV}=1
export OMFG_LAYER_MODE=${MODE}
export OMFG_LAYER_LOG_FILE=${REMOTE_BASE}/omfg-vkcube.log
export OMFG_BLEND_ADAPTIVE_STRENGTH=${OMFG_BLEND_ADAPTIVE_STRENGTH:-}
export OMFG_BLEND_ADAPTIVE_BIAS=${OMFG_BLEND_ADAPTIVE_BIAS:-}
export OMFG_SEARCH_BLEND_RADIUS=${OMFG_SEARCH_BLEND_RADIUS:-}
export OMFG_REPROJECT_SEARCH_RADIUS=${OMFG_REPROJECT_SEARCH_RADIUS:-}
export OMFG_REPROJECT_PATCH_RADIUS=${OMFG_REPROJECT_PATCH_RADIUS:-}
export OMFG_REPROJECT_CONFIDENCE_SCALE=${OMFG_REPROJECT_CONFIDENCE_SCALE:-}
export OMFG_REPROJECT_DISOCCLUSION_SCALE=${OMFG_REPROJECT_DISOCCLUSION_SCALE:-}
export OMFG_REPROJECT_HOLE_FILL_STRENGTH=${OMFG_REPROJECT_HOLE_FILL_STRENGTH:-}
export OMFG_REPROJECT_HOLE_FILL_RADIUS=${OMFG_REPROJECT_HOLE_FILL_RADIUS:-}
export OMFG_REPROJECT_GRADIENT_CONFIDENCE_WEIGHT=${OMFG_REPROJECT_GRADIENT_CONFIDENCE_WEIGHT:-}
export OMFG_REPROJECT_CHROMA_WEIGHT=${OMFG_REPROJECT_CHROMA_WEIGHT:-}
export OMFG_REPROJECT_AMBIGUITY_SCALE=${OMFG_REPROJECT_AMBIGUITY_SCALE:-}
export OMFG_MULTI_BLEND_COUNT=${OMFG_MULTI_BLEND_COUNT:-}
export OMFG_MULTI_SWAPCHAIN_MAX_GENERATED_FRAMES=${OMFG_MULTI_SWAPCHAIN_MAX_GENERATED_FRAMES:-}
export OMFG_ADAPTIVE_MULTI_MIN_GENERATED_FRAMES=${OMFG_ADAPTIVE_MULTI_MIN_GENERATED_FRAMES:-}
export OMFG_ADAPTIVE_MULTI_MAX_GENERATED_FRAMES=${OMFG_ADAPTIVE_MULTI_MAX_GENERATED_FRAMES:-}
export OMFG_ADAPTIVE_MULTI_INTERVAL_THRESHOLD_MS=${OMFG_ADAPTIVE_MULTI_INTERVAL_THRESHOLD_MS:-}
export OMFG_ADAPTIVE_MULTI_TARGET_FPS=${OMFG_ADAPTIVE_MULTI_TARGET_FPS:-}
export OMFG_ADAPTIVE_MULTI_INTERVAL_SMOOTHING_ALPHA=${OMFG_ADAPTIVE_MULTI_INTERVAL_SMOOTHING_ALPHA:-}
export OMFG_BFI_PERIOD=${OMFG_BFI_PERIOD:-}
export OMFG_BFI_HOLD_MS=${OMFG_BFI_HOLD_MS:-}
export OMFG_VISUAL_HOLD_MS=${OMFG_VISUAL_HOLD_MS:-}
export OMFG_PRESENT_TIMING=${OMFG_PRESENT_TIMING:-}
export OMFG_PRESENT_WAIT=${OMFG_PRESENT_WAIT:-}
export OMFG_PRESENT_WAIT_TIMEOUT_NS=${OMFG_PRESENT_WAIT_TIMEOUT_NS:-}
export OMFG_BENCHMARK=${OMFG_BENCHMARK:-}
export OMFG_BENCHMARK_LABEL=${OMFG_BENCHMARK_LABEL:-}
export VK_LAYER_PATH=${REMOTE_BASE}
export VK_INSTANCE_LAYERS=${OMFG_LAYER_NAME}
printf 'RUN impl=%s display=%s xauthority=%s mode=%s layer=%s count=%s present_mode=%s extra=%s target_fps=%s min_generated=%s max_generated=%s multi_swapchain_cap=%s reproj_disocc_scale=%s reproj_hole_fill_strength=%s reproj_hole_fill_radius=%s reproj_gradient_confidence=%s reproj_chroma_weight=%s reproj_ambiguity_scale=%s bfi_period=%s bfi_hold_ms=%s visual_hold_ms=%s present_timing=%s present_wait=%s present_wait_timeout_ns=%s benchmark=%s benchmark_label=%s\n' "${OMFG_LAYER_IMPL}" "\$DISPLAY" "\$XAUTHORITY" "\$OMFG_LAYER_MODE" "\$VK_INSTANCE_LAYERS" "${VKCUBE_COUNT}" "${VKCUBE_PRESENT_MODE:-default}" "${VKCUBE_EXTRA_ARGS:-none}" "${OMFG_ADAPTIVE_MULTI_TARGET_FPS:-default}" "${OMFG_ADAPTIVE_MULTI_MIN_GENERATED_FRAMES:-default}" "${OMFG_ADAPTIVE_MULTI_MAX_GENERATED_FRAMES:-default}" "${OMFG_MULTI_SWAPCHAIN_MAX_GENERATED_FRAMES:-default}" "${OMFG_REPROJECT_DISOCCLUSION_SCALE:-default}" "${OMFG_REPROJECT_HOLE_FILL_STRENGTH:-default}" "${OMFG_REPROJECT_HOLE_FILL_RADIUS:-default}" "${OMFG_REPROJECT_GRADIENT_CONFIDENCE_WEIGHT:-default}" "${OMFG_REPROJECT_CHROMA_WEIGHT:-default}" "${OMFG_REPROJECT_AMBIGUITY_SCALE:-default}" "${OMFG_BFI_PERIOD:-default}" "${OMFG_BFI_HOLD_MS:-default}" "${OMFG_VISUAL_HOLD_MS:-default}" "${OMFG_PRESENT_TIMING:-default}" "${OMFG_PRESENT_WAIT:-default}" "${OMFG_PRESENT_WAIT_TIMEOUT_NS:-default}" "${OMFG_BENCHMARK:-default}" "${OMFG_BENCHMARK_LABEL:-default}"
timeout ${VKCUBE_TIMEOUT_SEC}s vkcube --c ${VKCUBE_COUNT} --suppress_popups --wsi xcb ${PRESENT_MODE_ARG} ${VKCUBE_EXTRA_ARGS} > ${REMOTE_BASE}/vkcube.stdout 2>&1 || status=\$?
printf 'VCUBE_STATUS=%s\n' "\${status:-0}"
ls -lah ${REMOTE_BASE}
printf '\n--- vkcube.stdout ---\n'
sed -n '1,200p' ${REMOTE_BASE}/vkcube.stdout || true
printf '\n--- omfg-vkcube.log ---\n'
sed -n '1,260p' ${REMOTE_BASE}/omfg-vkcube.log || true
EOF
)

"${ROOT_DIR}/scripts/steamdeck-run.sh" "${REMOTE_SCRIPT}"
"${ROOT_DIR}/scripts/steamdeck-scp-from.sh" "${REMOTE_BASE}/vkcube.stdout" "${ARTIFACT_DIR}/vkcube.stdout"
"${ROOT_DIR}/scripts/steamdeck-scp-from.sh" "${REMOTE_BASE}/omfg-vkcube.log" "${ARTIFACT_DIR}/omfg-vkcube.log"

echo "Artifacts saved under ${ARTIFACT_DIR}"
